version: '3.1'

services:
  react-frontend:
      tty: true
      image: node:16
      container_name: react-frontend
      volumes: 
        - ./:/home/react-frontend
      ports:
        - 80:80
        - 3000:3000
        - 443:443
        - 8080:8080
      working_dir: /home/react-frontend